### ISSUE TITLE
SearchInputView is disappearing when rotating the device

### ISSUE THREAD

**Issue by spiralni** [arimorty/floatingsearchview#218] opened 2017-04-21 14:11 UTC
I found this issue and I need your help.
When I open the app (does not matter if it is in portrait or landscape mode) everthing is fine
![screenshot_2017-04-21-00-35-07](https://cloud.githubusercontent.com/assets/339101/25281151/b3bad3e0-2669-11e7-8870-64bc0d6a4073.png)

But when I rotate the device, the SearchInputView in the searchview get lost.
![screenshot_2017-04-21-00-35-15](https://cloud.githubusercontent.com/assets/339101/25281153/b3d932c2-2669-11e7-99f2-cc6e0e6223d5.png)

I even can type a word and the search is working, but it displays nothing I typed 
![screenshot_2017-04-21-00-35-35](https://cloud.githubusercontent.com/assets/339101/25281154/b3e5a16a-2669-11e7-9b98-791467b221e4.png)

Any comment?

**Comment by spiralni** [comment] 2017-04-21 14:23
It never backs to normal once the issue arises

**Comment by spiralni** [comment] 2017-04-22 05:54
I made further investigations and I discovered this is happening just when using activities. When using fragments the app behaves correctly.

This is a simple project hightighting the problem.

https://drive.google.com/open?id=0BwHzuXXGXF2BRENYRWZWRE1SbXM

**Comment by spiralni** [comment] 2017-04-22 15:23
Ok, this is getting weird.

Using the demo code

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

        showFragment(new DemoFragment()); //<- HERE I CREATE THE FloatingSearchView
    }
```

This **work as expected**, please notice the **onCreateView**, when changing orientation, is called twice in this scenario
```
LOADING FRAGMENT THE FIRST TIME

04-22 09:06:26.353 666-666/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onCreateView: demo
04-22 09:06:26.385 666-666/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onResume: demo

CHANGING ORIENTATION

04-22 09:07:20.119 666-666/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onPause: demo
04-22 09:07:20.127 666-666/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onStop: demo
04-22 09:07:20.222 666-666/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onCreateView: demo
04-22 09:07:20.251 666-666/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onCreateView: demo
04-22 09:07:20.270 666-666/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onResume: demo
```

But If I ensure the fragment does not get replaced if it already exists, using this code

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

        DemoFragment fragment = (DemoFragment) getSupportFragmentManager().findFragmentById(R.id.fragment_container);

        if (fragment == null) {
            showFragment(new DemoFragment()); //<- HERE I CREATE THE FloatingSearchView
        }
    }
```


This **does not work**, please notice the **onCreateView**,  when changing orientation, is called just once in this scenario.

```
LOADING FRAGMENT THE FIRST TIME

04-22 09:00:48.898 26962-26962/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onCreateView: demo
04-22 09:00:48.919 26962-26962/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onResume: demo

CHANGING ORIENTATION

04-22 09:01:11.983 26962-26962/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onPause: demo
04-22 09:01:12.076 26962-26962/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onCreateView: demo
04-22 09:01:12.100 26962-26962/ni.com.spiralni.myfloatingsearchview D/DemoFragment: onResume: demo

```

So using an activity, there is no chance the FloatingSearchView is created twice, resulting in the bug.
Any idea?

**Comment by arimorty** [comment] 2017-04-23 14:24
@spiralni there appears to be some issues to look at on orientation change. Will have a look at it. Thanks for including the project, it speeds up things.

Thanks fro contributing!
Ari

**Comment by Sammiches327** [comment] 2017-04-30 19:31
@arimorty any updates on this?

**Comment by LionZXY** [comment] 2017-05-01 15:14
Yeah. Any update?

**Comment by LionZXY** [comment] 2017-05-01 15:29
Any fork?

**Comment by alla-dubovska** [comment] 2017-05-05 16:10
This issue is presented also when having two fragments (the first one is with search view). Opining the first one, then the second one and returning to the first one leads to the same behavior.

**Comment by LionZXY** [comment] 2017-05-06 16:01
I have exactly the same bug. Can I help with this task?

**Comment by alla-dubovska** [comment] 2017-05-08 08:23
Also version 2.0.3 works fine without this bug. So the quick workaround is to roll back to it.

**Comment by hoangbkit** [comment] 2017-05-09 07:36
I got the same bug :( any luck ?

**Comment by vheerdenn** [comment] 2017-05-30 06:31
Hi, I wanted to use this library in a project of mine, but couldn't really use it with this bug. I debugged it and found that the issue was caused by:

File : FloatingSearchView.java
Line : 839
mSearchInput.setTextSize(mQueryTextSize);

If you comment that line out it works again.
Not sure how to fix it so the functionality works again.
I hope this helps.

**Comment by arimorty** [comment] 2017-06-04 20:58
@spiralni 👍 for providing the sample project highlighting the issue. The issue is fixed on dev [here](https://github.com/arimorty/floatingsearchview/compare/develop#diff-29f28ef0a7e4f183bc38ded5463b5ad2R1849) and will be part of next release (2.1.0)

**Comment by arimorty** [comment] 2017-06-04 22:48
@spiralni 👍 for providing the sample problem highlighting the issue.

**Closed as completed by arimorty** 2017-06-04 22:48 UTC
Labels: bug, fix is in develop
